"""added tags

Revision ID: 5ae9c888ac5c
Revises: 82b591a0b6c9
Create Date: 2026-05-13 21:45:32.127710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae9c888ac5c'
down_revision: Union[str, Sequence[str], None] = '82b591a0b6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tags',
    sa.Column('book_uid', sa.UUID(), nullable=False, foreign_key='books.uid'),
    sa.Column('tag_uid', sa.UUID(), nullable=False, foreign_key='tags.uid'),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid')
    )
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('book_tags')
    # ### end Alembic commands ###
