"""added unique constraint to reviews

Revision ID: 652887828d3e
Revises: 37b71f34c3af
Create Date: 2026-06-04 22:15:58.726651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '652887828d3e'
down_revision: Union[str, Sequence[str], None] = '37b71f34c3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_book_review', 'reviews', ['user_uid', 'book_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
