"""adding user following feature

Revision ID: 78a667c804c2
Revises: 2bc3b14306ed
Create Date: 2026-06-07 21:12:10.017178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78a667c804c2'
down_revision: Union[str, Sequence[str], None] = '2bc3b14306ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follows',
    sa.Column('follower_uid', sa.UUID(), nullable=False),
    sa.Column('following_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['follower_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_uid', 'following_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follows')
    # ### end Alembic commands ###
