"""added CASCADE on reviews.book_uid

Revision ID: 84997f78ef16
Revises: 652887828d3e
Create Date: 2026-06-04 22:21:38.876293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84997f78ef16'
down_revision: Union[str, Sequence[str], None] = '652887828d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_book_uid_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_book_uid_fkey', 'reviews', 'books', ['book_uid'], ['uid'])
    # ### end Alembic commands ###
