"""added fk to tags

Revision ID: 9b233c24e839
Revises: 5ae9c888ac5c
Create Date: 2026-05-13 21:51:12.896834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b233c24e839'
down_revision: Union[str, Sequence[str], None] = '5ae9c888ac5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'book_tags', 'tags', ['tag_uid'], ['uid'])
    op.create_foreign_key(None, 'book_tags', 'books', ['book_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    # ### end Alembic commands ###
