"""added liked_by many-to-many relationship between users and reviews

Revision ID: ed0ccea31391
Revises: 84997f78ef16
Create Date: 2026-06-04 22:56:35.479221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed0ccea31391'
down_revision: Union[str, Sequence[str], None] = '84997f78ef16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_likes',
    sa.Column('review_uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_uid'], ['reviews.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_uid', 'user_uid')
    )
    op.drop_constraint('book_tags_tag_uid_fkey', 'book_tags', type_='foreignkey')
    op.drop_constraint('book_tags_book_uid_fkey', 'book_tags', type_='foreignkey')
    op.create_foreign_key(None, 'book_tags', 'tags', ['tag_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_tags', 'books', ['book_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.drop_constraint(None, 'book_tags', type_='foreignkey')
    op.create_foreign_key('book_tags_book_uid_fkey', 'book_tags', 'books', ['book_uid'], ['uid'])
    op.create_foreign_key('book_tags_tag_uid_fkey', 'book_tags', 'tags', ['tag_uid'], ['uid'])
    op.drop_table('review_likes')
    # ### end Alembic commands ###
